version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: django-container-base:latest
    ports:
     - "8000:8000"
    volumes:
     - .:/opt/app
    environment:
     - POSTGRESQL_DATABASE=django-container
     - POSTGRESQL_USER=user
     - POSTGRESQL_PASSWORD=password
  # this image is meant for development: having shell in the app
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: django-container-dev:latest
    tty: true
    stdin_open: true
    command: bash -l
  db:
    image: praiskup/postgresql:APIv1.0.1-fedora23
    volumes:
      - ./deployment/postgresql/:/usr/share/cont-volume/postgresql/
      - ./db:/var/lib/pgsql/data
    environment:
     - CONT_DEBUG=3
     - POSTGRESQL_DATABASE=django-container
     - POSTGRESQL_USER=user
     - POSTGRESQL_PASSWORD=password
     - POSTGRESQL_CONTAINER_OPTS=clear_pgdata_pidfile = true
  #   migrator:
  #     build: .
  #     environment:
  #      - POSTGRESQL_DATABASE=trello-reporting
  #      - POSTGRESQL_USER=user
  #      - POSTGRESQL_PASSWORD=password
  #      - API_KEY
  #     volumes:
  #      - .:/opt/app/
  #     links:
  #      - db
  #     command: bash -c "ncat -v -w 30 db 5432 && python /opt/app/manage.py makemigrations && exec python /opt/app/manage.py migrate --no-input"
