FROM django-container-base

USER root
RUN dnf install -y nginx npm

# we will serve static assets from this container
RUN npm install -g bower

COPY deployment/nginx/nginx.conf /etc/nginx/
COPY deployment/nginx/django-container.conf /etc/nginx/conf.d/

# TODO: install patternfly

CMD ["/usr/sbin/nginx"]
