web:
  build: .
  ports:
   - "8000:8000"
  volumes: []
  links:
   - db
  tty: true
  environment:
   - POSTGRESQL_DATABASE=trello-reporting
   - POSTGRESQL_USER=user
   - POSTGRESQL_PASSWORD=password
   - API_KEY
db:
  image: praiskup/postgresql:APIv1.0.1-fedora23
  volumes:
    - ./deployment/postgresql/:/usr/share/cont-volume/postgresql/
    - ./db:/var/lib/pgsql/data
  environment:
   - CONT_DEBUG=3
   - POSTGRESQL_DATABASE=trello-reporting
   - POSTGRESQL_USER=user
   - POSTGRESQL_PASSWORD=password
   - POSTGRESQL_CONTAINER_OPTS=clear_pgdata_pidfile = true
migrator:
  build: .
  environment:
   - POSTGRESQL_DATABASE=trello-reporting
   - POSTGRESQL_USER=user
   - POSTGRESQL_PASSWORD=password
   - API_KEY
  volumes:
   - .:/opt/app/
  links:
   - db
  command: bash -c "sleep 5 && python /opt/app/manage.py makemigrations && exec python /opt/app/manage.py migrate --no-input"
