# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
- hosts: all
  gather_facts: false
  tasks:
    - raw: "[ -f /usr/bin/python ] || dnf install -y /usr/bin/python"
    - raw: "rpm -q python2-dnf || dnf install -y python2-dnf"
- hosts: web
  tasks:
    - name: Install required packages
      shell: "dnf clean all && dnf install -y python-pip python-psycopg2"
    - name: Add deployment user
      user:
        name: app
        state: present
        createhome: yes
        home: /opt/app
    # this can be incredibly slow: copy as few files as possible
    - name: Copy source
      copy:
        src: "{{ item }}"
        dest: /opt/app
        owner: app
      with_items:
        - "/ansible-container/the_project"
        - "/ansible-container/requirements.txt"
        - "/ansible-container/manage.py"
    - name: Install python requirements
      pip:
        requirements: /opt/app/requirements.txt
#    - name: Wait for postgres
#      wait_for:
#        host: db
#        port: 5432
#        delay: 10
#    - name: Apply database migrations
#      command: python manage.py migrate --noinput
#      args:
#        chdir: /opt/app
#      remote_user: app
